# Generated by Django 5.1.7 on 2025-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('NumberOfAttempts', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('DateOfVisit', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
